const { ipcMain, BrowserWindow, dialog } = require('electron')
const fs = require('fs')
const authService = require('./authService')
const db = require('./database')
const syncService = require('./syncService')
const presenceService = require('./presenceService')
const emailService = require('./emailService')
const api = require('./apiClient')

function esc (value) {
  return String(value == null ? '' : value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))
}

function money (value) {
  return Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function formatDateTime (value) {
  if (!value) return '—'
  const d = new Date(value)
  return d.toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' }) + ' ' + d.toLocaleTimeString('en-PH', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true })
}

function transactionPdfHtml (tx = {}) {
  const typeLabel = tx.type === 'cash_in' ? 'Cash In' : tx.type === 'cash_out' ? 'Cash Out' : (tx.type || '—')
  const statusLabel = tx.status ? String(tx.status).charAt(0).toUpperCase() + String(tx.status).slice(1) : '—'
  return `<!doctype html><html><head><meta charset="utf-8"/>
    <style>
      *{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;margin:0;padding:40px;color:#111827;background:#fff}
      .receipt{max-width:760px;margin:0 auto;border:1px solid #e5e7eb;border-radius:18px;overflow:hidden}
      .head{padding:28px 32px;background:linear-gradient(135deg,#1d4ed8,#4c6ef5);color:#fff}
      .brand{font-size:28px;font-weight:800;margin:0}.sub{margin:5px 0 0;font-size:13px;opacity:.9}.badge{display:inline-block;margin-top:14px;padding:6px 12px;border-radius:999px;background:rgba(255,255,255,.18);font-size:12px;font-weight:700}
      .body{padding:30px 32px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px 34px}.item{border-bottom:1px solid #f3f4f6;padding-bottom:14px}.lbl{font-size:11px;font-weight:800;color:#9ca3af;letter-spacing:.5px;text-transform:uppercase;margin-bottom:7px}.val{font-size:15px;font-weight:700;color:#111827}.amount{font-size:28px;color:#4c6ef5}.fee{color:#f59e0b}.foot{padding:18px 32px;background:#f8faff;color:#6b7280;font-size:12px;display:flex;justify-content:space-between}.pill{display:inline-block;padding:5px 12px;border-radius:999px;background:#d1fae5;color:#065f46;font-weight:800;font-size:12px}
    </style></head><body>
    <div class="receipt">
      <div class="head"><h1 class="brand">CashPOS</h1><p class="sub">Transaction Reference Details</p><div class="badge">Reference No. ${esc(tx.transaction_id || '—')}</div></div>
      <div class="body"><div class="grid">
        <div class="item"><div class="lbl">Reference Number</div><div class="val">${esc(tx.transaction_id || '—')}</div></div>
        <div class="item"><div class="lbl">Date & Time</div><div class="val">${esc(formatDateTime(tx.created_at))}</div></div>
        <div class="item"><div class="lbl">Customer</div><div class="val">${esc(tx.customer_name || 'Walk-in')}</div></div>
        <div class="item"><div class="lbl">Type</div><div class="val">${esc(typeLabel)}</div></div>
        <div class="item"><div class="lbl">Amount</div><div class="val amount">₱${money(tx.amount)}</div></div>
        <div class="item"><div class="lbl">Service Fee</div><div class="val fee">₱${money(tx.service_fee)}</div></div>
        <div class="item"><div class="lbl">Status</div><div class="val"><span class="pill">${esc(statusLabel)}</span></div></div>
        <div class="item"><div class="lbl">Sync Status</div><div class="val">${esc(tx.sync_status || '—')}</div></div>
      </div></div>
      <div class="foot"><span>Generated by CashPOS</span><span>${esc(formatDateTime(new Date().toISOString()))}</span></div>
    </div></body></html>`
}

function registerIpcHandlers () {
  const handlerNames = [
    'auth:login', 'auth:logout', 'auth:getSession', 'auth:getRemembered',
    'db:get-summary', 'db:get-transactions', 'db:add-transaction', 'db:update-transaction', 'db:delete-transaction', 'db:delete-test-data',
    'staff:list', 'staff:create', 'staff:update', 'staff:delete',
    'sync:status', 'sync:force', 'connectivity:check',
    'email:send-report', 'pdf:save-transaction',
    'settings:get', 'settings:set',
    'updater:check', 'updater:download', 'updater:install', 'updater:getVersion'
  ]
  handlerNames.forEach((name) => {
    try { ipcMain.removeHandler(name) } catch (e) {}
  })

  ipcMain.handle('auth:login', async (event, { username, password, role, rememberMe }) => {
    try {
      console.log('auth:login attempt for', username, 'role', role)
      const result = await authService.login(username, password, role, { rememberMe: !!rememberMe })
      if (!result.success) {
        console.log('auth:login failed for', username, result.error)
        return result
      }
      console.log('auth:login success for', username, result.offline ? '(offline cache)' : '(cloud)')
      return result
    } catch (err) {
      console.error('auth:login error', err)
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('auth:logout', async () => {
    try {
      return await authService.logout()
    } catch (err) {
      console.error('auth:logout error', err)
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('auth:getSession', async () => {
    const user = authService.getCurrentUser()
    if (!user) return { success: false, user: null }
    return { success: true, user }
  })

  ipcMain.handle('auth:getRemembered', async () => {
    return { success: true, remembered: authService.getRememberedLogin() }
  })

  ipcMain.handle('db:get-summary', async () => {
    authService.requireSession()
    return await db.getSummary(authService.getOwnerUsername())
  })

  ipcMain.handle('db:get-transactions', async (event, opts = {}) => {
    authService.requireSession()
    return await db.getTransactions({ ...opts, ownerUsername: authService.getOwnerUsername() })
  })

  ipcMain.handle('db:add-transaction', async (event, tx) => {
    try {
      authService.requireSession()
      return await db.addTransaction(tx, authService.getOwnerUsername())
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('db:update-transaction', async (event, id, updates) => {
    try {
      authService.requireSession()
      const safe = db.sanitizeTransactionUpdates(updates || {})
      if (db.updatesTouchMoneyFields(safe)) {
        authService.requireAdmin()
      }
      return await db.updateTransaction(id, safe, authService.getOwnerUsername())
    } catch (err) {
      return { success: false, error: err.message, changes: 0 }
    }
  })

  ipcMain.handle('db:delete-transaction', async (event, id) => {
    try {
      authService.requireAdmin()
      const owner = authService.getOwnerUsername()
      const result = await db.deleteTransaction(id, owner)
      // Best-effort immediate cloud delete; queue covers offline / failures.
      const token = authService.getApiToken()
      if (token && result && result.reference_number) {
        try {
          const online = await require('./apiClient').isOnline()
          if (online) {
            await require('./apiClient').deleteTransaction(token, result.reference_number)
            const pending = db.getPendingCloudDeletes(owner, 50)
            const match = pending.find(r => r.reference_number === result.reference_number)
            if (match) db.clearPendingCloudDelete(match.id, owner)
          }
        } catch (e) {
          console.warn('Immediate cloud delete failed; queued for sync', e && e.message)
        }
      }
      return result
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('db:delete-test-data', async () => {
    try {
      authService.requireAdmin()
      return await db.deleteTestData(authService.getOwnerUsername())
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('staff:list', async (event, opts = {}) => {
    try {
      authService.requireAdmin()
      const rows = await db.listUsers({
        ...opts,
        ownerUsername: authService.getOwnerUsername(),
        staffOnly: true
      })
      return { success: true, rows: rows || [] }
    } catch (err) {
      console.error('staff:list error', err.message)
      return { success: false, error: err.message, rows: [] }
    }
  })

  ipcMain.handle('staff:create', async (event, payload) => {
    try {
      authService.requireAdmin()
      return { success: true, data: await authService.createStaffAccount(payload) }
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('staff:update', async (event, id, payload) => {
    try {
      authService.requireAdmin()
      return { success: true, data: await authService.updateStaffAccount(id, payload) }
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('staff:delete', async (event, id) => {
    try {
      authService.requireAdmin()
      return { success: true, data: await authService.deleteStaffAccount(id) }
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('sync:status', async () => {
    // Read-only status for the 3s UI poll — do NOT heartbeat here (spam / soft-degrade risk).
    const status = await syncService.getStatus()
    let presence = null
    try { presence = presenceService.getPresenceState() } catch (e) {}
    return { ...status, presence }
  })

  ipcMain.handle('sync:force', async () => {
    return await syncService.forceSync()
  })

  ipcMain.handle('connectivity:check', async () => {
    const status = await syncService.refreshConnectionStatus()
    const presence = await presenceService.pulseIfLoggedIn()
    return { ...status, presence }
  })

  ipcMain.handle('email:send-report', async (event, payload) => {
    try {
      authService.requireAdmin()
      return await emailService.sendReportEmail(payload)
    } catch (err) {
      console.error('email:send-report error', err)
      return { success: false, error: err.message }
    }
  })

  // Local app settings (API URL etc.) — separate from renderer localStorage UI prefs.
  const { setApiEndpoint, resolveApiEndpoint } = require('../config/constants')
  const settingsStore = new (require('electron-store'))({ name: 'gcashpos-settings' })
  ipcMain.handle('settings:get', async (event, key) => {
    if (!key) return settingsStore.store
    return settingsStore.get(key)
  })
  ipcMain.handle('settings:getApiEndpoint', async () => resolveApiEndpoint())
  ipcMain.handle('settings:testConnection', async () => {
    const online = await api.isApiOnline()
    return { online, endpoint: resolveApiEndpoint() }
  })
  ipcMain.handle('settings:set', async (event, key, value) => {
    if (!key) return { success: false, error: 'Missing settings key' }
    if (key === 'apiEndpoint') {
      const normalized = setApiEndpoint(String(value || '').trim())
      return { success: true, apiEndpoint: normalized }
    }
    settingsStore.set(key, value)
    return { success: true }
  })

  const updateService = require('./updateService')
  ipcMain.handle('updater:check', async (event, manual) => updateService.checkForUpdates(!!manual))
  ipcMain.handle('updater:download', async () => updateService.downloadUpdate())
  ipcMain.handle('updater:install', async () => updateService.installUpdate())
  ipcMain.handle('updater:getVersion', async () => updateService.getCurrentVersion())
  ipcMain.handle('updater:isEnabled', async () => updateService.isUpdaterEnabled())

  ipcMain.on('ui:toast', (event, payload) => {
    BrowserWindow.getAllWindows().forEach((win) => {
      if (win && !win.isDestroyed()) {
        try { win.webContents.send('ui:toast', payload || {}) } catch (e) {}
      }
    })
  })

  ipcMain.handle('pdf:save-transaction', async (event, txOrId) => {
    let pdfWin
    try {
      authService.requireSession()
      const owner = authService.getOwnerUsername()
      let tx = null
      const id = (txOrId && typeof txOrId === 'object') ? txOrId.id : txOrId
      if (id != null) {
        tx = db.getTransactionById(id, owner)
      }
      if (!tx) {
        return { success: false, error: 'Transaction not found for this shop' }
      }

      const parent = BrowserWindow.fromWebContents(event.sender)
      const ref = String(tx.transaction_id || 'transaction').replace(/[^a-z0-9-]/gi, '_')
      const save = await dialog.showSaveDialog(parent, {
        title: 'Save Transaction PDF',
        defaultPath: `reference-${ref}.pdf`,
        filters: [{ name: 'PDF Files', extensions: ['pdf'] }]
      })
      if (save.canceled || !save.filePath) return { success: false, canceled: true }

      pdfWin = new BrowserWindow({ show: false, webPreferences: { offscreen: true } })
      await pdfWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(transactionPdfHtml(tx)))
      const data = await pdfWin.webContents.printToPDF({ printBackground: true, pageSize: 'A4', margins: { marginType: 'default' } })
      fs.writeFileSync(save.filePath, data)
      return { success: true, filePath: save.filePath }
    } catch (err) {
      console.error('pdf:save-transaction error', err)
      return { success: false, error: err.message }
    } finally {
      if (pdfWin && !pdfWin.isDestroyed()) pdfWin.close()
    }
  })
}

module.exports = { registerIpcHandlers }

