const { ipcMain, BrowserWindow, dialog } = require('electron')
const fs = require('fs')
const authService = require('./authService')
const db = require('./database')
const syncService = require('./syncService')
const emailService = require('./emailService')

function esc (value) {
  return String(value == null ? '' : value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))
}

function money (value) {
  return Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function formatDateTime (value) {
  if (!value) return '—'
  const d = new Date(value)
  return d.toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' }) + ' ' + d.toLocaleTimeString('en-PH', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true })
}

function transactionPdfHtml (tx = {}) {
  const typeLabel = tx.type === 'cash_in' ? 'Cash In' : tx.type === 'cash_out' ? 'Cash Out' : (tx.type || '—')
  const statusLabel = tx.status ? String(tx.status).charAt(0).toUpperCase() + String(tx.status).slice(1) : '—'
  return `<!doctype html><html><head><meta charset="utf-8"/>
    <style>
      *{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;margin:0;padding:40px;color:#111827;background:#fff}
      .receipt{max-width:760px;margin:0 auto;border:1px solid #e5e7eb;border-radius:18px;overflow:hidden}
      .head{padding:28px 32px;background:linear-gradient(135deg,#1d4ed8,#4c6ef5);color:#fff}
      .brand{font-size:28px;font-weight:800;margin:0}.sub{margin:5px 0 0;font-size:13px;opacity:.9}.badge{display:inline-block;margin-top:14px;padding:6px 12px;border-radius:999px;background:rgba(255,255,255,.18);font-size:12px;font-weight:700}
      .body{padding:30px 32px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px 34px}.item{border-bottom:1px solid #f3f4f6;padding-bottom:14px}.lbl{font-size:11px;font-weight:800;color:#9ca3af;letter-spacing:.5px;text-transform:uppercase;margin-bottom:7px}.val{font-size:15px;font-weight:700;color:#111827}.amount{font-size:28px;color:#4c6ef5}.fee{color:#f59e0b}.foot{padding:18px 32px;background:#f8faff;color:#6b7280;font-size:12px;display:flex;justify-content:space-between}.pill{display:inline-block;padding:5px 12px;border-radius:999px;background:#d1fae5;color:#065f46;font-weight:800;font-size:12px}
    </style></head><body>
    <div class="receipt">
      <div class="head"><h1 class="brand">GCash POS</h1><p class="sub">Transaction Reference Details</p><div class="badge">Reference No. ${esc(tx.transaction_id || '—')}</div></div>
      <div class="body"><div class="grid">
        <div class="item"><div class="lbl">Reference Number</div><div class="val">${esc(tx.transaction_id || '—')}</div></div>
        <div class="item"><div class="lbl">Date & Time</div><div class="val">${esc(formatDateTime(tx.created_at))}</div></div>
        <div class="item"><div class="lbl">Customer</div><div class="val">${esc(tx.customer_name || 'Walk-in')}</div></div>
        <div class="item"><div class="lbl">Type</div><div class="val">${esc(typeLabel)}</div></div>
        <div class="item"><div class="lbl">Amount</div><div class="val amount">₱${money(tx.amount)}</div></div>
        <div class="item"><div class="lbl">Service Fee</div><div class="val fee">₱${money(tx.service_fee)}</div></div>
        <div class="item"><div class="lbl">Status</div><div class="val"><span class="pill">${esc(statusLabel)}</span></div></div>
        <div class="item"><div class="lbl">Sync Status</div><div class="val">${esc(tx.sync_status || '—')}</div></div>
      </div></div>
      <div class="foot"><span>Generated by GCash POS</span><span>${esc(formatDateTime(new Date().toISOString()))}</span></div>
    </div></body></html>`
}

function registerIpcHandlers () {
  try { ipcMain.removeHandler('email:send-report') } catch (e) {}
  try { ipcMain.removeHandler('pdf:save-transaction') } catch (e) {}

  ipcMain.handle('auth:login', async (event, { username, password, role }) => {
    try {
      console.log('auth:login attempt for', username)
      const user = await authService.verifyUser(username, password, role)
      if (!user) {
        console.log('auth:login failed for', username)
        return { success: false, error: 'Invalid credentials' }
      }
      console.log('auth:login success for', username)
      return { success: true, user }
    } catch (err) {
      console.error('auth:login error', err)
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('db:get-summary', async () => {
    return await db.getSummary()
  })

  ipcMain.handle('db:get-transactions', async (event, opts = {}) => {
    return await db.getTransactions(opts)
  })

  ipcMain.handle('db:add-transaction', async (event, tx) => {
    try {
      return await db.addTransaction(tx)
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('db:update-transaction', async (event, id, updates) => {
    return await db.updateTransaction(id, updates)
  })

  ipcMain.handle('db:delete-transaction', async (event, id) => {
    return await db.deleteTransaction(id)
  })

  ipcMain.handle('db:delete-test-data', async () => {
    return await db.deleteTestData()
  })

  ipcMain.handle('staff:list', async (event, opts = {}) => {
    return await db.listUsers(opts)
  })

  ipcMain.handle('staff:create', async (event, payload) => {
    try {
      return { success: true, data: await authService.createStaffAccount(payload) }
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('staff:update', async (event, id, payload) => {
    try {
      return { success: true, data: await authService.updateStaffAccount(id, payload) }
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('staff:delete', async (event, id) => {
    try {
      return { success: true, data: await db.deleteUser(id) }
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('sync:status', async () => {
    return await syncService.getStatus()
  })

  ipcMain.handle('sync:force', async () => {
    return await syncService.forceSync()
  })

  ipcMain.handle('email:send-report', async (event, payload) => {
    try {
      return await emailService.sendReportEmail(payload)
    } catch (err) {
      console.error('email:send-report error', err)
      return { success: false, error: err.message }
    }
  })

  ipcMain.handle('pdf:save-transaction', async (event, tx) => {
    let pdfWin
    try {
      const parent = BrowserWindow.fromWebContents(event.sender)
      const ref = String(tx && tx.transaction_id ? tx.transaction_id : 'transaction').replace(/[^a-z0-9-]/gi, '_')
      const save = await dialog.showSaveDialog(parent, {
        title: 'Save Transaction PDF',
        defaultPath: `reference-${ref}.pdf`,
        filters: [{ name: 'PDF Files', extensions: ['pdf'] }]
      })
      if (save.canceled || !save.filePath) return { success: false, canceled: true }

      pdfWin = new BrowserWindow({ show: false, webPreferences: { offscreen: true } })
      await pdfWin.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(transactionPdfHtml(tx)))
      const data = await pdfWin.webContents.printToPDF({ printBackground: true, pageSize: 'A4', margins: { marginType: 'default' } })
      fs.writeFileSync(save.filePath, data)
      return { success: true, filePath: save.filePath }
    } catch (err) {
      console.error('pdf:save-transaction error', err)
      return { success: false, error: err.message }
    } finally {
      if (pdfWin && !pdfWin.isDestroyed()) pdfWin.close()
    }
  })
}

module.exports = { registerIpcHandlers }

